packages:
  - 'apps/*'
  - '!apps/legacy-frontend'
  - 'packages/*'
  - 'lambdas'
  - 'infra'
allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  lmdb: false
  msgpackr-extract: false
  protobufjs: true
