#!/usr/bin/env python3
"""
Generate a SQL migration that sets 20_m_producto.id_tipo_producto from the
xls CATEGORÍA column of 'Productos Serfel.xls'.

Match key: xls 'CÓD ALT' (strip the leading 'C'/'c') == 20_m_producto.cod_serfel
           e.g. 'C33331' -> 33331.
Value    : xls 'CATEGORÍA' (1..6) -> id_tipo_producto. These ids already exist
           in 20_p_tipo_producto (seeded by 0005), so the prod_tipo_prod foreign
           key is satisfied without touching the parent table.

Rows are grouped by category into one UPDATE ... WHERE cod_serfel IN (...) per
category, so the whole migration is 6 UPDATEs (plus audit-field bumps). Rows
with a blank CÓD ALT (186 of them) have no cod_serfel to match and are skipped.
Every xls cod_serfel is unique, so no code maps to two categories.
"""
import re
import sys
from collections import defaultdict
from pathlib import Path

import xlrd

ROOT = Path(__file__).resolve().parent.parent
XLS = ROOT / "packages/db/dump/Productos Serfel.xls"
# Drizzle custom migration (applied by the migrate Lambda / `pnpm db:migrate`).
OUT = ROOT / "packages/db/migrations/0009_update_producto_categoria.sql"
REPORT = ROOT / "packages/db/dump/update-producto-categoria.report.txt"

# Drizzle splits migration files on this marker and runs each chunk as one
# statement on a single connection (so the @uid session var persists).
BREAKPOINT = "\n--> statement-breakpoint\n"

USUARIO_MOD = 2
CATEGORIA_IDS = {1, 2, 3, 4, 5, 6}

# column indices (row 0 is the header)
C_CAT, C_ALT = 1, 3


def stripped_cod(alt):
    """Return int cod_serfel from 'C1234' / 'c1234', or None if no usable code."""
    a = "" if alt is None else str(alt).strip()
    if isinstance(alt, float) and alt == int(alt):
        a = str(int(alt))
    if a and a[0] in ("C", "c"):
        a = a[1:]
    a = a.strip()
    return int(a) if re.fullmatch(r"\d+", a) else None


def main():
    sh = xlrd.open_workbook(str(XLS)).sheet_by_index(0)

    by_cat = defaultdict(list)      # id_tipo_producto -> [cod_serfel, ...]
    seen = {}                       # cod_serfel -> id_tipo_producto (collision guard)
    n_no_alt = 0
    bad_cat = defaultdict(int)
    collisions = []

    for r in range(1, sh.nrows):
        cod = stripped_cod(sh.cell_value(r, C_ALT))
        if cod is None:
            n_no_alt += 1
            continue
        try:
            cat = int(float(sh.cell_value(r, C_CAT)))
        except (TypeError, ValueError):
            cat = None
        if cat not in CATEGORIA_IDS:
            bad_cat[str(sh.cell_value(r, C_CAT))] += 1
            continue
        if cod in seen and seen[cod] != cat:
            collisions.append((cod, seen[cod], cat))
            continue
        if cod in seen:
            continue
        seen[cod] = cat
        by_cat[cat].append(cod)

    header = (
        "-- Custom SQL migration file, put your code below! --\n"
        "-- Auto-generated by scripts/gen-update-producto-categoria.py from\n"
        "-- 'Productos Serfel.xls'. Sets 20_m_producto.id_tipo_producto from the\n"
        "-- xls CATEGORÍA, matching xls CÓD ALT (leading 'C' stripped) against\n"
        "-- 20_m_producto.cod_serfel. One UPDATE per category.\n"
        "SET NAMES utf8mb4;"
    )
    stmts = [header, f"SET @uid := {USUARIO_MOD};"]

    total = 0
    for cat in sorted(by_cat):
        cods = by_cat[cat]
        total += len(cods)
        in_list = ", ".join(str(c) for c in cods)
        stmts.append(
            "UPDATE `20_m_producto` SET "
            f"`id_tipo_producto` = {cat}, "
            "`id_usuario_mod` = @uid, `ult_fecha_mod` = NOW() "
            f"WHERE `cod_serfel` IN ({in_list});"
        )

    OUT.write_text(BREAKPOINT.join(stmts) + "\n", encoding="utf-8")

    rep = [
        f"xls rows                : {sh.nrows - 1}",
        f"matched (cod_serfel set): {total}",
        f"no CÓD ALT (skipped)    : {n_no_alt}",
        f"category out of range   : {dict(bad_cat)}",
        f"cod->2 categories (skip): {collisions[:10]} (n={len(collisions)})",
        "per category            : "
        + ", ".join(f"{c}:{len(by_cat[c])}" for c in sorted(by_cat)),
    ]
    REPORT.write_text("\n".join(rep), encoding="utf-8")

    print(f"Wrote {OUT.relative_to(ROOT)}")
    print(f"Wrote {REPORT.relative_to(ROOT)}")
    print(f"matched={total} no_alt={n_no_alt} bad_cat={dict(bad_cat)} "
          f"collisions={len(collisions)}")


if __name__ == "__main__":
    main()
