#!/usr/bin/env python3
"""
Generate the Drizzle custom migration 0006_seed_stock.sql: set 50_m_stock
(id_bodega = 1, the only warehouse) from the STOCK column of 'Productos Serfel.xls'.

Runs AFTER 0005_seed_productos, so every xls product already exists. Per row we
resolve the same @pid the productos migration used, then upsert the stock:

  * keyed (CÓD ALT present): match on cod_serfel, preferring the active row then
    the most recently modified (same tie-break as 0005).
  * no CÓD ALT: those 186 products were inserted with cod_serfel = 0, so match on
    cod_serfel = 0 AND nom_producto (the 8 no-key rows with stock have unique names).

Empty STOCK -> cantidad 0 (every product gets a row). Negatives kept as-is.
Idempotent: PK is (id_bodega, id_producto) and we use ON DUPLICATE KEY UPDATE.
"""
import re
import unicodedata
from decimal import Decimal, InvalidOperation
from pathlib import Path

import xlrd

ROOT = Path(__file__).resolve().parent.parent
XLS = ROOT / "packages/db/dump/Productos Serfel.xls"
OUT = ROOT / "packages/db/migrations/0006_seed_stock.sql"
REPORT = ROOT / "packages/db/dump/seed-stock.report.txt"
BREAKPOINT = "\n--> statement-breakpoint\n"

ID_BODEGA = 1  # 'Bodega Central' - the only warehouse in this system

C_ALT, C_DESC, C_STOCK = 3, 6, 12


def fix_mojibake(s: str) -> str:
    """Must match the productos generator exactly so the no-key rows resolve the
    same product by nom_producto."""
    if not s:
        return s
    try:
        return s.encode("cp1252").decode("utf-8")
    except (UnicodeEncodeError, UnicodeDecodeError):
        return s


def txt(v) -> str:
    if v is None:
        return ""
    if isinstance(v, float):
        v = str(int(v)) if v == int(v) else str(v)
    return fix_mojibake(str(v)).strip()


def qstr(v, maxlen=None) -> str:
    s = txt(v)
    if maxlen is not None:
        s = s[:maxlen]
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def stripped_cod(alt):
    a = txt(alt)
    if a and a[0] in ("C", "c"):
        a = a[1:]
    a = a.strip()
    return int(a) if a.isdigit() else None


def cantidad(v) -> str:
    """decimal(18,3) literal; blank -> 0.000, negatives kept."""
    if txt(v) == "":
        return "0.000"
    try:
        return f"{Decimal(str(v)):.3f}"
    except (InvalidOperation, ValueError):
        return "0.000"


def main():
    sh = xlrd.open_workbook(str(XLS)).sheet_by_index(0)

    header = (
        "-- Custom SQL migration file, put your code below! --\n"
        "-- Auto-generated by scripts/gen-seed-stock.py from 'Productos Serfel.xls'.\n"
        "-- Upserts 50_m_stock at bodega 1 from the STOCK column. Runs after 0005.\n"
        "SET NAMES utf8mb4;"
    )
    stmts = [header]

    n_keyed = n_nokey = n_zero = n_neg = 0
    for r in range(1, sh.nrows):
        cod = stripped_cod(sh.cell_value(r, C_ALT))
        cant = cantidad(sh.cell_value(r, C_STOCK))
        if cant == "0.000" and txt(sh.cell_value(r, C_STOCK)) == "":
            n_zero += 1
        if cant.startswith("-"):
            n_neg += 1

        if cod is not None:
            n_keyed += 1
            stmts.append(
                "SET @pid := (SELECT `id_producto` FROM `20_m_producto` "
                f"WHERE `cod_serfel` = {cod} "
                "ORDER BY (`id_estado` = 1) DESC, `ult_fecha_mod` DESC LIMIT 1);"
            )
        else:
            n_nokey += 1
            nom = qstr(sh.cell_value(r, C_DESC), 200)
            # nom_producto is a latin1 column; widen it to utf8mb4 (lossless) so
            # both sides of the comparison are utf8mb4 -- avoids "Illegal mix of
            # collations" on strict servers without dropping any character. The
            # per-row scan of ~3000 products is negligible for this one-off.
            stmts.append(
                "SET @pid := (SELECT `id_producto` FROM `20_m_producto` "
                f"WHERE `cod_serfel` = 0 AND CONVERT(`nom_producto` USING utf8mb4) = {nom} "
                "ORDER BY `id_producto` DESC LIMIT 1);"
            )

        # upsert only if the product resolved (guard against a missing product)
        stmts.append(
            "INSERT INTO `50_m_stock` (`id_bodega`, `id_producto`, `cantidad`) "
            f"SELECT {ID_BODEGA}, @pid, {cant} WHERE @pid IS NOT NULL "
            "ON DUPLICATE KEY UPDATE `cantidad` = VALUES(`cantidad`);"
        )

    OUT.write_text(BREAKPOINT.join(stmts) + "\n", encoding="utf-8")

    rep = [
        f"xls rows        : {sh.nrows - 1}",
        f"keyed (cod_serfel): {n_keyed}",
        f"no-key (by name): {n_nokey}",
        f"blank STOCK -> 0: {n_zero}",
        f"negatives kept  : {n_neg}",
    ]
    REPORT.write_text("\n".join(rep), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    print(f"keyed={n_keyed} no_key={n_nokey} blank_zero={n_zero} negatives={n_neg}")


if __name__ == "__main__":
    main()
