// Generates src/environments/environment.gen.ts from env vars.
// SST StaticSite injects APP_* during `pnpm run build`; locally, export them
// or accept the localhost defaults.
import { writeFileSync } from "node:fs";

const cfg = {
  apiUrl: process.env.APP_API_URL ?? "http://localhost:3001",
  userPoolId: process.env.APP_USER_POOL_ID ?? "local-pool",
  userPoolClientId: process.env.APP_USER_POOL_CLIENT_ID ?? "local-client",
};

writeFileSync(
  new URL("../src/environments/environment.gen.ts", import.meta.url),
  `// GENERATED by scripts/gen-env.mjs — do not edit; do not commit real values.\n` +
    `export const environment = ${JSON.stringify(cfg, null, 2)} as const;\n`
);
console.log("environment.gen.ts written:", cfg);
