// GENERATED by scripts/gen-env.mjs — do not edit; do not commit real values.
export const environment = {
  apiUrl: "http://localhost:3001",
  userPoolId: "local-pool",
  userPoolClientId: "local-client",
} as const;
