// GENERATED by scripts/gen-env.mjs — do not edit; do not commit real values.
export const environment = {
  "apiUrl": "https://koc8806flf.execute-api.us-east-1.amazonaws.com",
  "userPoolId": "us-east-1_4GeCfknnx",
  "userPoolClientId": "5hgbevrp8qrc4g6o6m1fjdqs5n"
} as const;
