services:
  mariadb:
    image: mariadb:11.4
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: serfel
      MARIADB_DATABASE: serfel
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 24

volumes:
  mariadb-data:
